name: check-pushes

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  simple_tests:
    if: contains(github.event.head_commit.message, '%unit%')
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run slint
      - run: npm run test:jest

  build:
    if: contains(github.event.head_commit.message, '%build%')
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: npm ci
      - run: npm rebuild
      - run: npm run production

  pw_tests:
    if: contains(github.event.head_commit.message, '%pw_tests%')
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Install missing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2 libffi8 libx264-164
      - run: npm ci
      - run: npm run pw:install
      - run: npm run test:pw-linux

  pw_update:
    if: contains(github.event.head_commit.message, '%pw_update%')
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: npm ci
      - run: npm run pw:install
      - run: npm run test:pw-update-linux
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update PW-snapshot"

  cy_tests:
    if: contains(github.event.head_commit.message, '%cy_tests%')
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: npm ci
      - run: npm run test:cy

  cy_update:
    if: contains(github.event.head_commit.message, '%cy_update%')
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - run: npm ci
      - run: npm run test:cy:update
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CY-snapshot"

  notify:
    if: ${{ always() && contains(github.event.head_commit.message, '%tg_notify%')}}
    runs-on: ubuntu-22.04
    needs:
      - simple_tests
      - build
      - pw_tests
      - pw_update
      - cy_tests
      - cy_update

    steps:
      - name: Telegram success notification
        uses: VanyaMate/github-action-telegram-notification@v0.20
        with:
          success: ${{ job.status }}
          tg_bot_token: ${{ secrets.TG_TOKEN_BOT }}
          tg_chat_id: ${{ secrets.TG_CHAT_ID }}